### ISSUE TITLE
add user/permissions login feture as example

### ISSUE THREAD

**Issue by Boegie19** [strapi/nextjs-corporate-starter#16]

**Comment by agaitan026** [comment]
+1

**Comment by PaulBratslavsky** [comment]
@Boegie19 for the suggestion. Just tagging you for visibility. I will close this issue since we do not plan to add the current functionality.  

@agaitan026  The starter's goal was to create a starting point for a basic project for users to make it their own. 

I decided not to implement this issue because some folks may choose to use an auth provider like Github. Since many other options are available, I decided to keep this up to the user.
