### ISSUE TITLE
Fix Metadata/SEO

### ISSUE THREAD

**Issue by KennyAtCodin** [strapi/nextjs-corporate-starter#32]
On the pages and global content type, the SEO plugin should also be used. Also, it seems that the metadata is not loaded correctly for any of the pages, always the global values are used.

@PaulBratslavsky is that correct? I will try to implement this for the dynamic pages which I'm currently developing

**Comment by PaulBratslavsky** [comment]
@KennyAtCodin Since this is a basic starter Strapi example.  We did not implement all the features and just used it as a starting point.  Hence we only have the one example of using SEO. 

But I agree with you, we should add that to all the pages. 

If you like you can create a PR for this, but I will add it to the list of things to do. 

Thank you 🙂

**Comment by PaulBratslavsky** [comment]
SEO added for pages dynamically set from strapi admin using the seo component
