### ISSUE TITLE
UPDATE: Will be going over PR soon had to...

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/nextjs-corporate-starter#69]
Thank you all for your patients.  I will be going over the PR soon.  

Was waiting for the 4.12.1 release to add the security updates and import/export fix that prevented be from updating.

I recently just made the update https://github.com/strapi/nextjs-corporate-starter/pull/68

**Comment by alexandremana** [comment]
Hey Paul, Sorry to disturb, but there is something I don't understand, I tried a lot to solve this by myself, but I'm gone to see the demo backend of the project and I saw the same problem. 

The problem concern the column "content available in" in Article ( or other collection include locale i18n ), why in local mode these column return a good and why when the project is deployed, like on my project and in the demo ( [the demo](https://api-ytdmv.strapidemo.com/admin/content-manager/collectionType/api::article.article?page=1&pageSize=10&sort=title:ASC&plugins[i18n][locale]=en)), this not available and return "-" ??? 

Thanks so much. 
Alex

**Comment by PaulBratslavsky** [comment]
@alexandremana can you share some screenshots to give a bit more context on the issue you are running into.

**Comment by alexandremana** [comment]
Hi @PaulBratslavsky , 
Yes, to explain, the dark mode articles component's from my configuration. 
The light mode is from a local configuration of [nextjs-corporate-starter](https://github.com/strapi/nextjs-corporate-starter)
As I said before, I try the live demo of super admin Foodadvisor to see the same weird effect. 

just follow the link : 
https://strapi.io/demo
or with Git repo : 
https://github.com/strapi/foodadvisor

I follow the live demo to see if the bug was in production because sometimes values appear correctly on local environnement. By the way. locale implementation is correctly added to the database.

Thanks so much

<img width="1192" alt="Capture d’écran 2023-08-08 à 11 55 42" src="https://github.com/strapi/nextjs-corporate-starter/assets/114826558/70c8fbf7-1fc2-4a5b-9308-d9f3715e6a56">


<img width="1180" alt="Capture d’écran 2023-08-08 à 11 58 01" src="https://github.com/strapi/nextjs-corporate-starter/assets/114826558/641d7100-1aeb-49d2-a0c9-bd816c43b755">

**Comment by PaulBratslavsky** [comment]
@alexandremana this is relate to this bug and will be fixed in the next release https://github.com/strapi/strapi/issues/17523
