### ISSUE TITLE
Thanks and fetchAPI options

### ISSUE THREAD

**Issue by ulysse-lacour** [strapi/nextjs-corporate-starter#73]
Hi everyone, just spent the week-end discovering and tweaking the project, learned so much, it's a wonderfull project !
Since a few weeks I was working on creating a Strapi & Nuxt boilerplate with Typescript and recently decided to move to Next.js instead, I feel bless that such a good boilerplate exists !
I'd love to participate to the project when I'll be sure to have explored fully the project. Do you have a discord or something to chat about it ?

Despite my actual research I already have a question : what is the options params in fetchAPI for ? It's always used to add the bearer token to the request , why not including it inside fetchAPI function ?

Finally if some of you are willing to share some public repo where this boilerplate has been used I'd be really curious about it!

**Comment by PaulBratslavsky** [comment]
I am glad that you are enjoying the project. You can join us on Discord; we also have Strapi Open Office hours Monday - Friday from 12:30 pm CST, where you can join and chat with us.   https://discord.com/invite/strapi

It is a personal preference when to pass the bearer token. I did it this way because we currently have an internal token that we are using to authorize the next js app to make requests to Strapi. Still, you may have authenticated users with their own tokens in the future.

So having the fetch API function be as general as possible gives more flexibility. Still, you can always change it in your project.  

Hence the "starter project." 

The goal was to create a project that could be a good starting point rather than a completed project. It would add a lot of my own biases and preference.
