### ISSUE TITLE
Problem with Video/Image fetching data 

### ISSUE THREAD

**Issue by MrAndriy** [strapi/nextjs-corporate-starter#89]
Code from starter repo.
Seeding was successful.

Problem when I type all neccesary fields in content manager and submit all changes
In sections components :
- Large video
- Slider

When I added the blocks for the article namely the slider it does not return the image data

```
  {
    id: 2,
    __component: 'shared.video-embed',
    url: 'https://youtu.be/rfSWR3L21zc?si=yrhpM2j1_C-Tk9Va'
  },
  { id: 1, __component: 'shared.slider' }
]

⨯ src/app/[lang]/components/ImageSlider.tsx (26:20) @ data
 ⨯ TypeError: Cannot read properties of undefined (reading 'data')
    at Slideshow (./src/app/[lang]/components/ImageSlider.tsx:19:34)
  24 |     <div className="slide-container">
  25 |       <Fade>
> 26 |         {data.files.data.map((fadeImage: Image, index) => {
     |                    ^
  27 |           const imageUrl = getStrapiMedia(fadeImage.attributes.url);
  28 |           return (
  29 |             <div key={index}>
  ```
  
  also same on pages with Large video component.
  
  How to fix this?

**Comment by PaulBratslavsky** [comment]
Thanks I will add it to the list to check.  I think this is because it is not being populated when being fetched.

https://github.com/strapi/nextjs-corporate-starter/blob/main/frontend/src/app/%5Blang%5D/blog/%5Bcategory%5D/%5Bslug%5D/page.tsx

```
    const urlParamsObject = {
        filters: { slug },
        populate: {
            cover: { fields: ['url'] },
            authorsBio: { populate: '*' },
            category: { fields: ['name'] },
            blocks: { populate: '*' },
        },
    };
```

I believe we need to make the update here inside the blocks object to give more detailed instructions on what items you would like to populate. 

When I get a chance I will fix it here.  But here is a great resource around populate and filtering. https://strapi.io/blog/demystifying-strapi-s-populate-and-filtering

**Comment by PaulBratslavsky** [comment]
This was fixed in this PR https://github.com/strapi/nextjs-corporate-starter/pull/93
